#
# Umber Common HTTP.

services:

  umber.common.http.generate:
    class: 'Umber\Common\Http\HttpResponseGenerator'
    arguments:
      - '@umber.common.http.response.factory'
      - '@umber.common.serializer'
      - 'json'
    public: false

  umber.common.http.response.factory:
    class: 'Umber\Common\Http\Factory\HttpResponseFactory'
    public: false
